### PR TITLE
Warp events

### PR DESCRIPTION
**Pull request by MrDoubleA232**
Adds 3 new events:
- onWarpEnter(eventObj,warp,playerObj) and onPostWarpEnter(warp,playerObj), which run just before the warping starts.
- onWarp(warp,playerObj), which runs immediately after the player's position has been updated from warping.

Should make dealing with warps much easier, especially instant and portal warps, which were a hassle before.

Requires a change to [main_events.lua](https://cdn.discordapp.com/attachments/739951186857427005/1038434660725817354/main_events.lua) to add the events and a change to [editorevents.lua](https://cdn.discordapp.com/attachments/739951186857427005/1038434660230910004/editorevents.lua) to make it work with portal warps.

### CODE REVIEW

**Comment by MrDoubleA232** [comment]
I just noticed that this has 20 commits and 2000 changed files. I have no clue why.

**Comment by Wohlstand** [comment]
You got rid of 300k lines and added only 1.7k 👀

**Comment by Wohlstand** [comment]
You got rid of 300k lines and added only 3k 👀

Is that because you attempted to remove a part of Boost library?

**Comment by MrDoubleA232** [comment]
The only files I intended to change were RuntimeHook.h, RuntimeHookHooks.cpp, and RuntimeHookGeneral.cpp. But obviously... something went wrong lol

**Comment by Supermario1313** [comment]
Looks like the actual change is in the last commit, the other ones seem to be here because of a merge. There are even some duplicate commits for some reason.

image
image

**Comment by Bluenaxela** [comment]
Yeah... that's a bit of a git history mess with the way you've merged things around in your branch there. Would probably be best to do a fresh branch (or git reset) based on 19cedde1693ca22aaf196c3e471fe5f57c5d7c66 then `git cherry-pick 82742cf8182919a2a69af5372f64368be564524e`
Force-pushing that overtop of the [MrDoubleA232:warp-events](https://github.com/MrDoubleA232/LunaLua/tree/warp-events) branch would clean up this pull request.

**Comment by Bluenaxela** [comment]
The Git history mess notwithstanding the intended commit looks good to me. I'm looking at clearing up some merge requests, so I performed a cherry-pick of 82742cf8182919a2a69af5372f64368be564524e from [MrDoubleA232:warp-events](https://github.com/MrDoubleA232/LunaLua/tree/warp-events) and pushed it, so this is effectively merged now.

**Pull request closed without merging**
