### PR TITLE
Added movie sprite support

### PR DESCRIPTION
**Pull request by airpo**
I added a class called LuaMovieResource (derived from LuaImageResource) and some modification in existing classes.
This enables smbx to use movie files as sprite in the same way as image files.
If you are interested in this feature and need more information , please ask me.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Wow, interesting job!
Also, please update deploy.bat script to copy FFMPEG dll's to pack them into zip too :wink:

**Comment by airpo** [comment]
Updated!
I found that LunaLua version name(displayed on game start) has been modified to ours.
Feel free to change anything unwanted.

**Comment by Wohlstand** [comment]
Thanks! I'll show your works to my co-developers until merge, there are will be surprised with this.
Good job :+1:

**Comment by KevinW1998** [comment]
Wow, thank you! I will do a quick code check and will give feedback.

**Comment by KevinW1998** [comment]
Again, thank you for your work! This looks pretty awesome! I have a quick question though: Do you have an example level for the movie feature? I'll ask my co-dev Rednaxela if he has something to say for this.

**Comment by airpo** [comment]
Yes I have but this is going to take time to show for some reason. Please wait.

**Comment by KevinW1998** [comment]
You don't need to rush, we are patient ;)

**Comment by airpo** [comment]
Here is an example: https://www.dropbox.com/s/0kyjxjwesjp7wnu/mv_example.zip?dl=0 (with readme)

**Comment by airpo** [comment]
Here is the reference of LuaMovieResource in English!
[LuaMovieResource_reference_eng.txt](https://github.com/Wohlhabend-Networks/LunaDLL/files/149437/LuaMovieResource_reference_eng.txt)

**Comment by KevinW1998** [comment]
Thanks, I'll give it a try.

**Comment by Bluenaxela** [comment]
Interesting and nifty stuff. There are far too many things (i.e. zeriyoshi's spawning stuff, and some files that seem a bit specific to your project) mixed in here besides "Added movie sprite support" however to accept the pull request in bulk, but I'm certainly interested in merging some things.

I'll probably be able to start looking into merging some things toward the middle of this week.

Btw, I see a note where "Exclude ffi dependency." is mentioned in a roadmap for your fork? You may wish to be aware, we're planning to make **much** more extensive use of FFI in the future here. Specifically, it is the plan to be switching all of the classes for SMBX objects (i.e. NPC, Block, etc) to FFI-based implementations instead of based upon luabind, because that can perform substantially better in LuaJIT (I've done some testing of this with a Block class implementation) and it also takes much less code to implement these classes.

**Comment by airpo** [comment]
> There are however far far far too many things

I am really sorry about this. I should have made a new branch for this feature.(I am not familiar with git.)

About "Exclude ffi dependency.", what this mentions to is not LunaDll. To our lua scripts.
Before modifying LunaDll,we made our Dlls to use in lua through FFI. To enable FFI, we commented out some lines of mainV2.lua which disable FFI. But this is unsecure. So we are going to stop using our dlls(with ffi) and merge them into LunaDll. This is what "Exclude ffi dependency." means.
(We needed some hacks for hooking native NPC spawn process and networking related things) 

I am glad to contribute to your works. Thank you.

**Comment by KevinW1998** [comment]
"we commented out some lines of mainV2.lua which disable FFI". This does not disable FFI, it just disables the **access** to the FFI API.

**Comment by Wohlstand** [comment]
Okay, we are discussed and we are will merge your pull request into separated branch
Because before merge with master we are need to edit lots of files: texts, labels, configs, readmes, etc. which are adapted to your fork.

**Comment by Wohlstand** [comment]
Merged as separated branch.

**Comment by Wohlstand** [comment]
Also: I just tried your example: it's very funny :laughing: Good job :wink: ! :+1:

**Pull request closed without merging**
