### PR TITLE
Add options in luna.ini for wine compatibility

### PR DESCRIPTION
**Pull request by Supermario1313**
I've added a `run_when_unfocused` option in `luna.ini`. It serves as a more user-friendly way to fix SMBX2 not working with recent wine versions.

### CODE REVIEW

**Comment by Supermario1313** [comment]
I've added an additional `hide_window_after_testing` option to `luna.ini`. When it's set to false, the SMBX2 window won't hide when closing it during a testing session (the game won't run though). It was added to fix a bug with wine: when restarting a level from the editor, the game window won't display anything but a black screen, even though the game is still running.

**Comment by MrDoubleA232** [comment]
This is actually a global issue, not just a wine one.

**Comment by Supermario1313** [comment]
Oh, I didn't know about that. My Windows dual boot is kinda broken rn so I couldn't test it. Core and I both had this bug on Linux and I don't remember you reporting it despite using the latest build for your battle arena so I pretty much assumed that the problem was only on Linux.

**Comment by Bluenaxela** [comment]
Right, I'll definitely need to look into that. I have a bit of a hunch.

**Comment by Supermario1313** [comment]
In that case, do you think that `hide_window_after_testing` should be removed from the PR?

**Comment by Supermario1313** [comment]
A proper fix for this issue was added in 248bdd01cf29a7256531fc95299316c85a60b2a1 so I'm closing this pull request.

**Pull request closed without merging**
