### PR TITLE
Collision matrix

### PR DESCRIPTION
**Pull request by Supermario1313**
Improves MDA's collision groups systems (#40) by adding a collision matrix.

Requires changes to [`ffi_misc.lua`](https://gist.github.com/Supermario1313/3a576ea8b86858f250f0e87b9533f63f).

### CODE REVIEW

**Comment by Bluenaxela** [comment]
I'm curious if the string hashing overhead is notable if the overlapping NPC count gets high. If it does, a potential way to make it more efficient would be to map the strings to automatically assigned indices, but I'm not sure if this impact would be large enough to be worth doing or not though.

**Comment by Supermario1313** [comment]
I like this idea! I have three implementations in mind for the collision matrix itself:
- A `std::vector<bool>` containing the rows of a triangular array end-to-end
  - Pros: O(1) time complexity for reading the collision matrix
  - Cons: O(nGroups²) worst case time complexity when adding a new group, O(nGroups²) space complexity
- A `std::bitset<maxGroups>` containing the rows of a triangular array end-to-end
  - Pros: O(1) time complexity for reading the collision matrix and adding a new group
  - Cons: Only supports a fixed amount of collision groups, O(maxGroups²) space complexity
- A `std::unordered_map<IntegerGroupPair, bool>` similar to the current implementation
  - Pros: O(1) amortized time complexity for reading the collision matrix, adding a new group is free, O(nPairs) space complexity
  - Cons: O(nPairs) worst case time complexity for reading the collision matrix, potential hashing overhead

Which one do you think is the best?

**Comment by Bluenaxela** [comment]
Anything with a fixed limit or O(nGroups²) _space_ complexity seems like a bad plan to me. The full triangular matrix is often going to be very sparse and number of groups may become very high.

Keep in mind that one of the use cases of collision groups involves dynamically creating new groups per NPC that creates sub-NPCs that relate to it. It's for this reason I don't think anything with O(nGroups²) space complexity is acceptable, and also means that if we do map strings to IDs there would probably need to be refcounting to allow reuse of IDs.

`std::unordered_map<IntegerGroupPair, bool>` is one reasonable option certainly.

I find myself thinking a _very good_ tree-based implementation _might_ be better than a hash map here with the access patterns I expect (but I don't think `std::ordered_map` is a suitable tree for being efficient... don't think the standard library has a suitable tree container for this type of use case)

Another thought that comes to mind is that `std::vector<std::unordered_map<int, bool>>` could certainly be suitable.
Hard to say for sure what would be best among these without benchmarking though.

**Comment by ds-sloth** [comment]
Depending on how much you're willing to bank on sparseness, an alternative approach might be `std::vector<std::unique_ptr<std::vector<bool>>>`, so that only used rows exist in the matrix. It could be specified that non existent entries within each row are assumed to be false to prevent costly expansions when rows are added.

This is no more CPU-costly than a matrix of bools when the row doesn't exist (in fact it'd be more cache-friendly), and costlier by two indirections (pointer dereference, 2nd vector lookup) when it does.

In the strictly sparse case (n groups and k entries per group), it'd have O(kn) space complexity. However, in the worst case of dense entries, it would indeed have O(n^2) space complexity, and be slower and larger than a dense matrix.

**Comment by Bluenaxela** [comment]
One thought I just had: Only assigning IDs for groups explicitly used with the matrix (and not IDs for groups only used for preventing self-interaction within the one group), would likely reduce the expected sparseness dramatically.

There's no guarantee some per-instance groups won't want to set up matrix entries for more general categories as well though, so it still seems safest to avoid O(nGroups²) space complexity options just in case, but this thought might affect the tradeoffs between some options.

**Comment by Supermario1313** [comment]
I did some benchmarking and it seems that, if the amount of group pairs in the collision matrix is greater than ~40-60, `std::vector<std::unordered_map<int, bool>>` is faster than `std::vector<std::unique_ptr<std::vector<bool>>>` and the difference between them isn't that important for sparser collision matrices (at most ~0.5 s for 50000000 reads). Therefore, I think I'm gonna settle on the former implementation since it also has a better space complexity.

[Here's the code that I used for benchmarking, as well as two outputs.](https://gist.github.com/Supermario1313/012056d5517702100d7901ee4b19507d)

**Comment by Supermario1313** [comment]
Just thought about something. Instead of using a `std::vector<std::unordered_map<unsigned int, bool>>`, I can use a `std::vector<std::unordered_set<unsigned int>>`. `gCollisionMatrix[i].contains(j)` would be `true` if the value in the collision matrix is different from the default.

**Comment by Supermario1313** [comment]
I've just finished the re-implementation of the collision matrix with `std::vector<std::unordered_set<unsigned int>>`. This new implementation requires changes to [`ffi_block.lua`](https://gist.github.com/Supermario1313/a661473b87522b209db47bf7cc032ca1#file-ffi_block-lua), [`ffi_misc.lua`](https://gist.github.com/Supermario1313/a661473b87522b209db47bf7cc032ca1#file-ffi_misc-lua), [`ffi_npc.lua`](https://gist.github.com/Supermario1313/a661473b87522b209db47bf7cc032ca1#file-ffi_npc-lua) and [`main_events.lua`](https://gist.github.com/Supermario1313/a661473b87522b209db47bf7cc032ca1#file-main_events-lua). Furthermore, since collision group strings are now handled in lua, the 32 byte limit for collision groups has been removed.

**Comment by Supermario1313** [comment]
By the way, if someone has suggestions for improving deallocation and cleanup, I'm interested.

**Comment by Bluenaxela** [comment]
This is looking pretty good. I'll might need to review the deallocation/cleanup stuff a bit closer to some time to make sure there aren't gaps, but yeah.

Now... one little detail I do take a little bit of issue with is `default_behavior`. Is there any reason it's a function pointer? Nothing sets it at runtime, and there's just the one implementation. Also, if you did want another hypothetical future instance to have a different default behavior, why not just have a it be a virtual function? The compiler can also sometimes even do some optimizations to avoid a virtual lookup in certain cases too... though I'm not sure there's even reason to mark it virtual yet. It's pretty trivial to just have it be a function, and add the virtual keyword at a later point if a reason comes along.

**Comment by Supermario1313** [comment]
I don't use OOP constructs in C++ very often so I just forgot I could use a virtual method for that. But yeah, adding the virtual keyword later should be fine.

**Comment by Supermario1313** [comment]
Also, what do you thing about adding a `collidesWith` lua method which uses collision group indices behind the scenes to blocks, NPCs and players (once collision groups are implemented for them) to allow for more efficient collision group checking from the lua side?

**Pull request merged**
