### PR TITLE
Console clear command (console:clear())

### PR DESCRIPTION
**Pull request by ghost**
This is another pull request, this time pertaining to the Console class.

This adds a new function (console:clear()) which does what it says: It clears the console text itself, just like the Windows Command Prompt when you execute "cls".

ezgif-5-7e67602617

Can be useful for debugging, where the advanced user can clear the console window when loading another level and using console:println afterward.

### CODE REVIEW

**Comment by Emral** [comment]
Generally when it comes to debugging a process like this, you kinda wanna have the log of the entire process's lifetime in the console. If you wanna index when a new level is loaded (for example), you'd find more utility in doing a console:println("loading " .. targetLevelName). Clearing logs can bite you when you later realize that some useful info was cleared.
This all is to say that I don't really see much utility in this other than for a recreation of Bad Apple or leveraging this console to make a text adventure.
Just my 2 cents.

**Comment by Bluenaxela** [comment]
I'm with Emral, I'm not seeing a purpose to this...

That said, in principle it's simple enough and I'd be fine merging it were there no issues with the code.

I am seeing one one clear problem with the code currently though: Why is `coninfo` a global variable now??? This makes zero sense. The functions that use it don't need it to persist outside the lifetime of that function, so it should just be a variable on the stack in each function.

**Comment by ghost** [comment]
> I'm with Emral, I'm not seeing a purpose to this...
> 
> That said, in principle it's simple enough and I'd be fine merging it were there no issues with the code.
> 
> I am seeing one one clear problem with the code currently though: Why is `coninfo` a global variable now??? This makes zero sense. The functions that use it don't need it to persist outside the lifetime of that function, so it should just be a variable on the stack in each function.

It needs to be global for me to use the settings from the console window in order for me to execute the clear command.

Though yeah, now that I think about it, this Console function seems like a pointless idea... sorry about making this PR

**Comment by Bluenaxela** [comment]
> It needs to be global for me to use the settings from the console window in order for me to execute the clear command.

It doesn't need to though... `coninfo` is just a variable that gets filled out by the `GetConsoleScreenBufferInfo(...)` function, and you call that in both places `coninfo` is used. Nothing previously in `coninfo` from before the `GetConsoleScreenBufferInfo` lives on, nor is used by the call. The `coninfo` variable has no purpose except to receive data from the `GetConsoleScreenBufferInfo(...)` function.

**Pull request merged**
